### PR TITLE
Generator for Calculator based on YAML input and some bugfixes

### PR DESCRIPTION
**Pull request by c-bless**
Added a Python file "generate_calculator" that takes a YAML as input and generates a static calculator. 

static html files are therefore moved to folder "html". YAML file is placed in folder "config" and the calculator template is placed in folder "template"

### CODE REVIEW

**Comment by c-bless** [comment]
Also fixed an error with the label for "Threat Acot Access" which was called "Size" instead of "Access"

**Comment by c-bless** [comment]
Added  functionality for weighing the consequences. 

with following entries in YAML file

risk_weight:
  # ( TIF_LC + TIF_LI + TIF_LA + TIF_LAC ) / 4 = must result in "1" to be accepted
  TIF_LC: 1.5
  TIF_LI: 0.5
  TIF_LA: 1
  TIF_LAC: 1

the following JavaScript calculation of the TIF:

TIF = (+$("#lc").val() + +$("#li").val() + +$("#la").val() + +$("#lac").val()) / 4;

will be replaced by:

TIF = (+ ($("#lc").val()  * 1.5 )+ +($("#li").val() * 0.5 ) + + ($("#la").val()* 1 ) + + ($("#lac").val() * 1 )) / 4;

**Comment by c-bless** [comment]
Fixed a bug. Because my linter was complaining that there are duplicated IDs for "r". 

renamed: 
Overall Risk Severity: <span id="R"></span>
to:
Overall Risk Severity: <span id="Risk"></span>

to prevent confusion with id "r"

<h6>Recoverability</h6>
<select class="custom-select custom-select-sm" id="r"

**Comment by cutaway** [comment]
Can you move this to a branch? I would be easier to test and make updates before merging into the main branch. I might be able to do it. But it would make it easier. Perhaps a cbless-dev or dev-cbless branch?

**Comment by c-bless** [comment]
fixed issue #10  by submitting score vector as base64 encoded string and changing wrong abbreviations.

1. create base64 parameter via 'btoa' 
```
score_param = btoa(score)
$("#score").attr("href", "https://iacs-star-calculator.com/?vector=" + score_param);
```
2. decode parameter via 'atob' 
```
init(atob(getUrlParameter('vector')), getUrlParameter('v'));
```
3. fixed wrong abbrevations for div id numbers
```
var partials = ["sl", "m", "o", "a", "ea", "ee", "aw", "dr", "lc", "li", "la", "lac", "ed", "pd", "se", "r"];
```

**Comment by c-bless** [comment]
Added an addition variable to template file {{ filename }} that is set via the python script. The value is taken from filename variable of the YAML file which is referring the output filename. 

in YAML:
```
outfile:
  #specifing the filename of the output file that will be created in output folder "html"
  filename: iacs_star_calculator.html
```

in template:
```
$("#score").attr("href", "https://iacs-star-calculator.com/{{filename}}?vector=" + score_param);
```
                        
in output:
```
$("#score").attr("href", "https://iacs-star-calculator.com/iacs_star_calculator.html?vector=" + score_param);
```

**Comment by davisjessa28** [comment]
Excellent! I'm about to do a deep-dive for myself on our current
content--I've been buried in meetings and catch-up work after 3 weeks of
travel.

Do we have a meeting series on our calendar?

Don, I'll be at GridSecCon in Minneapolis, if you happen to be there.

Jessa

**Comment by cutaway** [comment]
@davisjessa28 I'll respond via email

**Pull request merged**
