### PR TITLE
Merge Weber-Dev into Main

### PR DESCRIPTION
**Pull request by cutaway**
The Weber-Dev branch started from the Cbless-Dev branch. I have provided several updates to fix things that were broken and update great ideas from @c-bless . Updates include, but are not limited to:

- Fixed typos and missing numbers in the calculator fields. (This addresses @jakesmithQUT's issue)
- Fixed vector score issue, building upon @c-bless approach. (This addresses @cutaway 's issue)
- Moving index.html file to root folder. 
- Updated generate_calculator.py script with additional functionality and comments. It should now run cross-platform on Linux and Windows.
- Updated the configuration file to include options and comments for additional control.
- Gave calculator templates a new extension and added new options and comment fields.
- Updated Readme file to reflect updates.

My goal is to get this update tested and moved into main. The site is currently pointing to the Weber-Dev branch for testing. Once merged I will switch to the main branch.

Demonstration values to show updated capabilities. Try the following: 
Use the following Vector Score in the "Republish Score Vector" field: 

(SL:1/M:3/O:6/A:8/EA:1/EE:3/AW:6/DR:9/LC:2/LI:4/LA:8/LAC:9/ED:7/PD:6/SE:2/R:0)

Use the following URL to populate from link: 

https://iacs-star-calculator.com/html/iacs_star_calculator.html?vector=KFNMOjEvTTozL086Ni9BOjgvRUE6MS9FRTozL0FXOjYvRFI6OS9MQzoyL0xJOjQvTEE6OC9MQUM6OS9FRDo3L1BEOjYvU0U6Mi9SOjAp

### CODE REVIEW

**Comment by c-bless** [comment]
In general I like the additions you made. But I had a problem on building the generator. 

1. Generator has been moved to scripts folder. When running it from project root "with scripts/generate_calculator.py" it cannot find directories for config and template files. 

```
(venv)  cb@xps-cb  ~/workspace/IACS_STAR_Methodology   weber-dev ±  scripts/generate_calculator.py -h      
usage: generate_calculator.py [-h] [-e] [-c FILENAME.yaml] [-t FILENAME.ctpl]

Generate a custom static IACS calculator file from YAML input.

options:
  -h, --help            show this help message and exit
  -e, --examples        Print a message to show command line examples. (default: False)
  -c FILENAME.yaml, --config FILENAME.yaml
                        Filename for the YAML configuration file. (default: default.yaml)
  -t FILENAME.ctpl, --template FILENAME.ctpl
                        Filename for the calculator's template file. (default: calculator_template.ctpl)
```


This can be fixed by getting the parent root  folder in generator script: 

```
iacs_dir           = os.path.dirname(os.path.dirname(__file__))
````


2. The python script sets output directory to "custom". This folder has not been commited to git yet. Either we create the directory and commit it to git or we should use "html" otherwise the generation fails (`FileNotFoundError: [Errno 2] No such file or directory: '.../IACS_STAR_Methodology/custom/custom-iacs_star_calculator.html'
`)



Furthermore I would like to add an additional section to YAML. 

```
target:
  schema: https
  host_port: iacs-star-calculator.com
```

This would allow to get rid of the lines in template: 

```
$('#score').text(score);
 /*$("#score").attr("href", "https://iacs-risk-rating.com/html/{{filename}}?vector=" + score_param);*/
/*$("#score").attr("href", "http://localhost:9000/html/{{filename}}?vector=" + score_param);*/
 $("#score").attr("href", "https://iacs-star-calculator.com/html/{{filename}}?vector=" + score_param);
                        
```

Replacement: 

```
$('#score').text(score);
$("#score").attr("href", "{{target.schema}}://{{target.host_port}}/html/{{filename}}?vector=" + score_param);
```

What do you think about that.? We than can create a second yaml with the following target: 
```
target:
  schema: http
  host_port: localhost:9000
```


If you like I can add those to your branch.

**Comment by cutaway** [comment]
Fixing these now. First update was addressed by adding a '.gitignore' file into the custom directory. This does two things. First, it makes the directory relevant since it has contents. Also, it prevents developers from uploading custom calculators. 

Fixing the scheme and link part now. I was considering something like that but you put context to it. 

Update should be fixed in a few.

**Comment by cutaway** [comment]
@c-bless Tested in Linux and Windows. Both working with current update. Target functionality added

**Comment by c-bless** [comment]
On my Manjaro system it works when changing the following row
```
iacs_dir           = os.path.dirname(os.getcwd())
```

and replace it with the following row.
```
iacs_dir           = parentdir = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
```

Everything else looks great.

**Comment by c-bless** [comment]
on my Manjaro machine it works  as well when changing the following line 

```
iacs_dir           = os.path.dirname(os.getcwd())
```

and replace it with: 
```
 iacs_dir           = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))
```

THis will gather the path from current file (generator script) and gets the parent directory.

**Comment by cutaway** [comment]
> os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))

Confirmed and updated. Merging to main. Thank you @c-bless

**Pull request merged**
